[package]
name = "assortedscans"
version = "0.1.3"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies.aidoku]
git = "https://github.com/Aidoku/aidoku-rs"

[dependencies.mangadventure_template]
path = "../../template"
